# Generated by Django 3.1 on 2020-08-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbClass', models.CharField(max_length=10)),
                ('verbs', models.TextField()),
            ],
        ),
    ]
